# Generated by Django 5.1.7 on 2025-01-XX XX:XX

from django.db import migrations, models


def set_edge_type_to_null(apps, schema_editor):
    """Set all edge_type values to NULL for existing DrawerLineItem records"""
    DrawerLineItem = apps.get_model('core', 'DrawerLineItem')
    DrawerLineItem.objects.all().update(edge_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doorlineitem_sand_cross_grain_doorlineitem_sand_edge'),
    ]

    operations = [
        # First, set all edge_type values to NULL
        migrations.RunPython(set_edge_type_to_null, migrations.RunPython.noop),
        
        # Remove the edge_type field from DrawerLineItem
        migrations.RemoveField(
            model_name='drawerlineitem',
            name='edge_type',
        ),
        
        # Delete the DrawerEdgeType model
        migrations.DeleteModel(
            name='DrawerEdgeType',
        ),
    ]






