# Generated by Django 5.1.7 on 2026-03-06 20:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customer_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional design charge (e.g., Arched=$5)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='panelrise',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional surcharge for this panel rise (e.g., Glaze=$2)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='paneltype',
            name='design_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Design charge for this panel type (e.g., Raised=$10, Flat=$6, Slab=$3.50)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
