# Generated by Django 5.1.7 on 2026-03-06 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pricing_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerDimensionSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, help_text='Width threshold in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('depth', models.DecimalField(decimal_places=2, default=0.0, help_text='Depth threshold in inches', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surcharge_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage surcharge applied when threshold is exceeded', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Drawer Dimension Surcharge',
                'verbose_name_plural': 'Drawer Dimension Surcharges',
                'ordering': ['surcharge_percent'],
            },
        ),
        migrations.RemoveField(
            model_name='defaultdrawersettings',
            name='surcharge_depth',
        ),
        migrations.RemoveField(
            model_name='defaultdrawersettings',
            name='surcharge_percent',
        ),
        migrations.RemoveField(
            model_name='defaultdrawersettings',
            name='surcharge_width',
        ),
    ]
