# Generated by Django 5.1.7 on 2026-03-06 21:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_drawerdimensionsurcharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorlineitem',
            name='height',
            field=models.DecimalField(decimal_places=3, help_text='Height in inches', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='doorlineitem',
            name='width',
            field=models.DecimalField(decimal_places=3, help_text='Width in inches', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='drawerlineitem',
            name='depth',
            field=models.DecimalField(decimal_places=3, help_text='Depth in inches', max_digits=6),
        ),
        migrations.AlterField(
            model_name='drawerlineitem',
            name='height',
            field=models.DecimalField(decimal_places=3, help_text='Height in inches', max_digits=6),
        ),
        migrations.AlterField(
            model_name='drawerlineitem',
            name='width',
            field=models.DecimalField(decimal_places=3, help_text='Width in inches', max_digits=6),
        ),
    ]
